### ISSUE TITLE
Freeze aléatoire du jeu au bout d'un certain temps 

### ISSUE THREAD

**Issue by alexandre-janniaux** [friendshipismagic/friendshipismagic#2]
Au bout d'un certain temps et dans des conditions aléatoires, le jeu se freeze. Cela pourrait potentiellement être dû au moteur d'intelligence artificielle.

En plus de cela, il faudrait rendre le jeu plus robuste aux lancements d'exceptions afin de pouvoir les déboguer plus facilement sans provoquer un crash violent du jeu.

**Comment by alexandre-janniaux** [comment]
Cela ressemble à une boucle infinie dans l'IA : 

`#0  std::_Bit_iterator_base::_Bit_iterator_base (this=0x7fffffffda30, __x=0x176a880, __y=0)
    at /usr/include/c++/7.1.1/bits/stl_bvector.h:142
#1  0x00000000004c5053 in std::_Bit_iterator::_Bit_iterator (this=0x7fffffffda60, __x=0x176a880, __y=14)
    at /usr/include/c++/7.1.1/bits/stl_bvector.h:223
#2  0x00000000004c542a in std::vector<bool, std::allocator<bool> >::operator[] (this=0x7fffffffdbb8, __n=14)
    at /usr/include/c++/7.1.1/bits/stl_bvector.h:858
#3  0x00000000004c4a4f in Dijkstra::dijkstra (this=0x7fffffffdbb0, player=82, mob=83)
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/ai/dijkstra/dijkstra.cpp:56
#4  0x00000000004c09c1 in AiInterface::setPath (this=0x175acd0, mobID=1, playerX=299.384064, playerY=564.05011, 
    mobX=398.644257, mobY=564.05011, g=...)
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/ai/ai/aiinterface.cpp:47
#5  0x00000000004c0b83 in AiInterface::giveOrder (this=0x175acd0, mobID=1, playerX=299.384064, playerY=564.05011, 
    mobX=398.644257, mobY=564.05011, g=...)
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/ai/ai/aiinterface.cpp:67
#6  0x0000000000513f46 in AISystem::update (this=0x175acb8, dt=...)
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/systems/aisystem.cpp:21
#7  0x00000000004d400e in World::update (this=0x1740d40, dt=...)
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/core/world.cpp:95
#8  0x000000000050c6b7 in GameState::update (this=0xad3490, dt=...)
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/states/gamestate.cpp:67
#9  0x000000000050f822 in StateStack::update (this=0x7fffffffdff0, dt=...)
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/states/statestack.cpp:39
#10 0x00000000004ccfd9 in Application::update (this=0x7fffffffdff0, dt=...)
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/core/application.cpp:58
#11 0x00000000004cd0d8 in Application::run (this=0x7fffffffdff0)
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/core/application.cpp:81
#12 0x00000000004cdae3 in main ()
    at /home/alexandre/projects/alexandre-janniaux/friendshipismagic/FriendshipIsMagic/jni/core/main.cpp:35
`
